### PR TITLE
Web: set cookie maxAge to allow for a persistent login

### LINKED ISSUE #48: Figure out why sessions don't last very long
After just a few minutes, the app no longer recognizes that the user is logged in even though the cookie still exists.

### PR DESCRIPTION
**Pull request by arschmitz**
Fixes gh-48

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Shouldn't the cookie options be passed to the cookieParser middleware?

**Comment by arschmitz** [comment]
i got this usage from.

http://stackoverflow.com/questions/10429557/whats-the-correct-way-to-use-maxage-with-express-js

**Comment by arschmitz** [comment]
also http://www.senchalabs.org/connect/session.html shows the same

**Comment by scottgonzalez** [comment]
I guess the docs do say this is the right way to set the length. Seems strange that they don't suggest setting the cookie options with the cookie middleware.

You need to sign your commit. And don't use `gh-` references, use `#`.

**Comment by arschmitz** [comment]
oh right used to jquery :) ill fix right now

**Comment by arschmitz** [comment]
Fixed

**Pull request merged**
